version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server  --loglevel verbose --appendonly yes --requirepass ${REDIS_PASS}
    volumes:
    - /c/Users/franc/Desktop/code/Dev/atomico3/redis-data:/data



  db:
    image: postgres:15
    container_name: container_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - /c/Users/franc/Desktop/code/Dev/atomico3/data:/var/lib/postgresql/data

volumes:
  db-data: